### ISSUE TITLE
NAX Support

### ISSUE THREAD

**Issue by Igoreshazhu** [beanieaxolotl/shinen-gax-python#1]
Did this program support NAX sound driver which used only in Crash Nitro Kart and Payload for N-GAGE? I'm looking for HQ rip of Payload which sounds too compressed.

**Comment by beanieaxolotl** [comment]
Yes! In fact, the program actually can pack/unpack NAX files (albeit saving them as .nax to avoid confusion with the ELF .o format). Some of my GAX research was actually done with the Payload .o files I had obtained.

_I completely forgot to include that fact in the readme though._ 

Full HQ ripping of the tracks: I might need to implement some sort of XM converter (like GaXM) or a high-quality GAX rendering engine for that to happen. This is something that I hope to achieve, too.
