### ISSUE TITLE
Implementation of GAX Sound Engine Music Styles, Remix with MIDI, and Export to mp3

### ISSUE THREAD

**Issue by Lubub-Fluffy** [beanieaxolotl/shinen-gax-python#12]
It needs to be implemented: GAX Sound Engine Music Styles, Remix with MIDI, export to mp3.

**Comment by beanieaxolotl** [comment]
- _GAX Sound Engine Music Styles:_ Music composition style templates are out of scope for the tracker. The closest thing I can do are preset instruments, but I am not that far into the project to do that yet.
-  _Remix with MIDI:_ ..I don't know what you mean.
-  _Export to MP3:_ Music rendering consists of a bunch of separate scripts (that aren't in the repo yet), and they only support real-time exporting to .raw and relies on the end-user to gauge when to stop export. I do plan to include some basic audio rendering export features, but I don't know about MP3 support right now.

**Comment by AnnoyedArt1256** [comment]
for exporting to WAV you could export the music with 2 (or any other amount of) loops, the loop count could be changed by the end user a la Furnace. To convert WAV's to MP3's you could use ffmpeg i think.

**Comment by LububTristarHomeVideo** [comment]
Also Have to import MIDI into GAX Sound Engine Tracker?
