### ISSUE TITLE
Iridion II (USA) ~ "shinen" and "credits" are missing

### ISSUE THREAD

**Issue by beanieaxolotl** [beanieaxolotl/shinen-gax-python#9]
This affects both the retail and prototype builds of this game.

**Comment by AnnoyedArt1256** [comment]
I think adding 42049hz to the list of mixing rates (in gax_constants.py) fixes this, since those two tunes use that sample rate.

**Comment by beanieaxolotl** [comment]
Oh. 
I looked into this and the reason this was happening was that I misremembered the last mixing rate value as 42029 Hz, when it should've been 42049 Hz. I corrected the error and 3 songs (including "gallery", which I had overlooked) are now able to be ripped. 
Thanks!
